## NumPy: the absolute basics for beginners
Welcome to the absolute beginner’s guide to NumPy! If you have comments or suggestions, please don’t hesitate to reach out!
#### Email Id : neil9130patil@gmail.com
#### Ph : 9130232390

### Welcome to NumPy!
NumPy (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems. NumPy users include everyone from beginning coders to experienced researchers doing state-of-the-art scientific and industrial research and development. The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

The NumPy library contains multidimensional array and matrix data structures (you’ll find more information about this in later sections). It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays. It adds powerful data structures to Python that guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.

Learn more about NumPy here!

Installing NumPy
To install NumPy, we strongly recommend using a scientific Python distribution. If you’re looking for the full instructions for installing NumPy on your operating system, you can find all of the details here.

If you already have Python, you can install NumPy with:

#### conda install numpy  or  pip install numpy

If you don’t have Python yet, you might want to consider using Anaconda. It’s the easiest way to get started. The good thing about getting this distribution is the fact that you don’t need to worry too much about separately installing NumPy or any of the major packages that you’ll be using for your data analyses, like pandas, Scikit-Learn, etc.

You can find all of the installation details in the Installation section at SciPy.

### How to import NumPy
Any time you want to use a package or library in your code, you first need to make it accessible.

In order to start using NumPy and all of the functions available in NumPy, you’ll need to import it. This can be easily done with this import statement:

(We shorten numpy to np in order to save time and also to keep code standardized so that anyone working with your code can easily understand and run it.)

In [2]:
import numpy as np

### What’s the difference between a Python list and a NumPy array?
NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them. While a Python list can contain different data types within a single list, all of the elements in a NumPy array should be homogenous. The mathematical operations that are meant to be performed on arrays would be extremely inefficient if the arrays weren’t homogenous.

### Why use NumPy?

NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

### What is an array?
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

An array can be indexed by a tuple of nonnegative integers, by booleans, by another array, or by integers. The rank of the array is the number of dimensions. The shape of the array is a tuple of integers giving the size of the array along each dimension.

One way we can initialize NumPy arrays is from Python lists, using nested lists for two- or higher-dimensional data.

For Example

In [3]:
a = np.array([1,2,3,4,5,6])

In [6]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [8]:
a, b

(array([1, 2, 3, 4, 5, 6]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

We can access the elements in the array using square brackets. When you’re accessing elements, remember that indexing in NumPy starts at 0. That means that if you want to access the first element in your array, you’ll be accessing element “0”.

In [9]:
print(a[0])

1


In [10]:
print(b[0])

[1 2 3 4]


## More information about arrays
This section covers 1D array, 2D array, ndarray, vector, matrix

You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on. The NumPy ndarray class is used to represent both matrices and vectors. A vector is an array with a single dimension (there’s no difference between row and column vectors), while a matrix refers to an array with two dimensions. For 3-D or higher dimensional arrays, the term tensor is also commonly used.

#### What are the attributes of an array?

An array is usually a fixed-size container of items of the same type and size. The number of dimensions and items in an array is defined by its shape. The shape of an array is a tuple of non-negative integers that specify the sizes of each dimension.

In NumPy, dimensions are called axes. This means that if you have a 2D array that looks like this:

[[0., 0., 0.],

 [1., 1., 1.]]

Your array has 2 axes. The first axis has a length of 2 and the second axis has a length of 3.

Just like in other Python container objects, the contents of an array can be accessed and modified by indexing or slicing the array. Unlike the typical container objects, different arrays can share the same data, so changes made on one array might be visible in another.

Array attributes reflect information intrinsic to the array itself. If you need to get, or even set, properties of an array without creating a new array, you can often access an array through its attributes.

### How to create a basic array
This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

To create a NumPy array, you can use the function np.array().

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list. You can find more information about data types here.

https://numpy.org/doc/1.19/reference/arrays.ndarray.html#arrays-ndarray

https://numpy.org/doc/1.19/reference/arrays.html#arrays

https://numpy.org/doc/1.19/reference/arrays.dtypes.html#arrays-dtypes

In [11]:
import numpy as np
a = np.array([1,2,3,4])

You can visualize your array this way:
![](https://numpy.org/doc/1.19/_images/np_array.png)

Be aware that these visualizations are meant to simplify ideas and give you a basic understanding of NumPy concepts and mechanics. Arrays and array operations are much more complicated than are captured here!

Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

In [12]:
np.zeros(2)

array([0., 0.])

Or an array filled with 1’s:

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [19]:
# Create an empty array with 2 elements
np.empty(2) #may vary

array([0., 0.])

You can create an array with a range of elements:

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.

In [22]:
np.arange(5,10,2)

array([5, 7, 9])

You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [23]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### Specifying your data type
    
While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

In [25]:
np.array([1,2,3,4],dtype=np.int64)

array([1, 2, 3, 4])

In [26]:
np.ones(3, dtype=np.int16)

array([1, 1, 1], dtype=int16)

https://numpy.org/doc/1.19/user/quickstart.html #quickstart-array-creation

### Adding, removing, and sorting elements
This section covers np.sort(), np.concatenate()

Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

If you start with this array:

In [27]:
arr = np.array([1,3,5,6,8,4,9,7])

You can quickly sort the numbers in ascending order with:

In [28]:
np.sort(arr)

array([1, 3, 4, 5, 6, 7, 8, 9])

https://numpy.org/doc/1.19/reference/generated/numpy.sort.html#numpy.sort

If you start with these arrays:

In [3]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

You can concatenate them with np.concatenate().

In [30]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
import numpy as np
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

Or, if you start with these arrays:

In [11]:
x = np.array([[2,3],[5,6]])
y = np.array([[5,4]])

In [12]:
np.concatenate((x,y), axis=0)

array([[2, 3],
       [5, 6],
       [5, 4]])

In order to remove elements from an array, it’s simple to use indexing to select the elements that you want to keep.

To read more about concatenate, see: concatenate.
https://numpy.org/doc/1.19/reference/generated/numpy.concatenate.html#numpy.concatenate

### How do you know the shape and size of an array?
This section covers ndarray.ndim, ndarray.size, ndarray.shape

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

For example, if you create this array:

In [14]:
arr = np.array([[[1,2,3,4],[3,4,5,6]], [[4,5,6,7],[9,8,7,6]],[[9,7,5,4],[3,4,2,3]]])

In [15]:
arr

array([[[1, 2, 3, 4],
        [3, 4, 5, 6]],

       [[4, 5, 6, 7],
        [9, 8, 7, 6]],

       [[9, 7, 5, 4],
        [3, 4, 2, 3]]])

To find the number of dimensions of the array, run:

In [16]:
arr.ndim

3

And to find the shape of your array, run:

In [17]:
arr.shape

(3, 2, 4)

To find the total number of elements in the array, run:

In [18]:
arr.size

24

#### Can you reshape an array?
This section covers arr.reshape()

Yes!

Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

If you start with this array:

In [19]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

You can use reshape() to reshape your array. For example, you can reshape this array to an array with three rows and two columns

In [20]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

With np.reshape, you can specify a few optional parameters:



In [26]:
d = np.reshape(b, newshape=(1,6), order='C')
d

array([[0, 1, 2, 3, 4, 5]])

b is the array to be reshaped.

newshape is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

order: C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

If you want to learn more about C and Fortran order, you can read more about the internal organization of NumPy arrays here. Essentially, C and Fortran orders have to do with how indices correspond to the order the array is stored in memory. In Fortran, when moving through the elements of a two-dimensional array as it is stored in memory, the first index is the most rapidly varying index. As the first index moves to the next row as it changes, the matrix is stored one column at a time. This is why Fortran is thought of as a Column-major language. In C on the other hand, the last index changes the most rapidly. The matrix is stored by rows, making it a Row-major language. What you do for C or Fortran depends on whether it’s more important to preserve the indexing convention or not reorder the data.

Learn more about shape manipulation here.
https://numpy.org/doc/1.19/user/quickstart.html#quickstart-shape-manipulation

### How to convert a 1D array into a 2D array (how to add a new axis to an array)¶
This section covers np.newaxis, np.expand_dims

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

For example, if you start with this array:

In [28]:
a = np.array([1,2,3,4,5,6])
print(a.shape)
print(a)

(6,)
[1 2 3 4 5 6]


You can use np.newaxis to add a new axis:

In [30]:
a2 = a[np.newaxis, :]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

In [32]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


Or, for a column vector, you can insert an axis along the second dimension:



In [33]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

For example, if you start with this array:

In [35]:
import numpy as np
a = np.array([1,2,3,4,5,6])
a.shape,a

((6,), array([1, 2, 3, 4, 5, 6]))

You can use np.expand_dims to add an axis at index position 1 with: or column vector

In [36]:
b = np.expand_dims(a, axis=1)
b.shape, b

((6, 1),
 array([[1],
        [2],
        [3],
        [4],
        [5],
        [6]]))

You can add an axis at index position 0 with: or row vector

In [37]:
c = np.expand_dims(a, axis=0)
c.shape, c

((1, 6), array([[1, 2, 3, 4, 5, 6]]))

Find more information about newaxis here and expand_dims at expand_dims.
https://numpy.org/doc/1.19/reference/arrays.indexing.html#arrays-indexing
https://numpy.org/doc/1.19/reference/generated/numpy.expand_dims.html#numpy.expand_dims

### Indexing and slicing
You can index and slice NumPy arrays in the same ways you can slice Python lists.

In [39]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [40]:
a[1]

2

In [41]:
a[1:]

array([2, 3])

In [42]:
a[:2]

array([1, 2])

In [43]:
a[:-1]

array([1, 2])

You can visualize it this way:
![](https://numpy.org/doc/1.19/_images/np_indexing.png)
You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

For example, if you start with this array:

In [44]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.

In [45]:
less_than_5 = a[a<5]
less_than_5

array([1, 2, 3, 4])

You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.

In [47]:
five_up = a[a>=5]
five_up

array([ 5,  6,  7,  8,  9, 10, 11, 12])

You can select elements that are divisible by 2:

In [48]:
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

Or you can select elements that satisfy two conditions using the & and | operators:



In [49]:
inbetween_2_11 = a[(a>2)&(a<11)]
inbetween_2_11

array([ 3,  4,  5,  6,  7,  8,  9, 10])

You can also make use of the logical operators & and | in order to return boolean values that specify whether or not the values in an array fulfill a certain condition. This can be useful with arrays that contain names or other categorical values.

In [51]:
five_up = (a>5)|(a==5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

You can also use np.nonzero() to select elements or indices from an array.

Starting with this array:

In [52]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

You can use np.nonzero() to print the indices of elements that are, for example, less than 5:



In [55]:
b = np.nonzero(a<5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In this example, a tuple of arrays was returned: one for each dimension. The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.

If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them. For example:

In [57]:
list_coordinate = list(zip(b[0],b[1]))
for item in list_coordinate:
    print(item)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


You can also use np.nonzero() to print the elements in an array that are less than 5 with:



In [58]:
less_than_5 = a[np.nonzero(a<5)]
less_than_5

array([1, 2, 3, 4])

If the element you’re looking for doesn’t exist in the array, then the returned array of indices will be empty. For example:

In [59]:
not_there = a[np.nonzero(a==45)]
not_there

array([], dtype=int64)

Learn more about indexing and slicing here and here.

Read more about using the nonzero function at: nonzero.
https://numpy.org/doc/1.19/user/quickstart.html#quickstart-indexing-slicing-and-iterating
https://numpy.org/doc/1.19/reference/generated/numpy.nonzero.html#numpy.nonzero

### How to create an array from existing data
This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

You can easily use create a new array from a section of an existing array.

Let’s say you have this array:

In [61]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

You can create a new array from a section of your array any time by specifying where you want to slice your array.

In [62]:
arr = a[3:6]
arr

array([4, 5, 6])

Here, you grabbed a section of your array from index position 3 through index position 8.

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [66]:
a1 = np.array([[1,2],[1,2]])
a2 = np.array([[3,4],[3,4]])
a1,a2

(array([[1, 2],
        [1, 2]]),
 array([[3, 4],
        [3, 4]]))

You can stack them vertically with vstack:

In [64]:
b = np.vstack((a1,a2))
b

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

Or stack them horizontally with hstack:

In [65]:
c = np.hstack((a1,a2))
c

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

You can split an array into several smaller arrays using hsplit. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

Let’s say you have this array:

In [67]:
x = np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

If you wanted to split this array into three equally shaped arrays, you would run:



In [75]:
b = np.hsplit(x,3)
b

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

If you wanted to split your array after the third and fourth column, you’d run:



In [73]:
c = np.hsplit(x,(4,6))
c

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6],
        [17, 18]]),
 array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

Learn more about stacking and splitting arrays here.
https://numpy.org/doc/1.19/user/quickstart.html#quickstart-stacking-arrays

You can use the view method to create a new array object that looks at the same data as the original array (a shallow copy).

Views are an important NumPy concept! NumPy functions, as well as operations like indexing and slicing, will return views whenever possible. This saves memory and is faster (no copy of the data has to be made). However it’s important to be aware of this - modifying data in a view also modifies the original array!

Let’s say you create this array:

In [77]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Now we create an array b1 by slicing a and modify the first element of b1. This will modify the corresponding element in a as well!

In [78]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [79]:
b1[0]=99
b1

array([99,  2,  3,  4])

In [80]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Using the copy method will make a complete copy of the array and its data (a deep copy). To use this on your array, you could run:

In [83]:
b1 = a.copy()

In [84]:
b1

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

https://numpy.org/doc/1.19/user/quickstart.html#quickstart-copies-and-views

### Basic array operations
This section covers addition, subtraction, multiplication, division, and more

Once you’ve created your arrays, you can start to work with them. Let’s say, for example, that you’ve created two arrays, one called “data” and one called “ones”
![](np_array_dataones.png)
You can add the arrays together with the plus sign.

In [110]:
data = np.array([1,2])
ones = np.ones(2,np.int)
data,ones

(array([1, 2]), array([1, 1]))

![](https://numpy.org/doc/1.19/_images/np_array_dataones.png)
You can, of course, do more than just addition!

In [112]:
data + ones

array([2, 3])

![](https://numpy.org/doc/1.19/_images/np_data_plus_ones.png)


In [89]:
data - ones

array([0, 1])

In [90]:
data*data

array([1, 4])

In [91]:
data/data

array([1., 1.])

![](https://numpy.org/doc/1.19/_images/np_sub_mult_divide.png)
Basic operations are simple with NumPy. If you want to find the sum of the elements in an array, you’d use sum(). This works for 1D arrays, 2D arrays, and arrays in higher dimensions.

In [92]:
a = np.array([1,2,3,4,5])
a.sum()

15

To add the rows or the columns in a 2D array, you would specify the axis.

If you start with this array:

In [93]:
b = np.array([[1,2,3],[5,6,7]])
b.sum(axis=0)

array([ 6,  8, 10])

In [94]:
b.sum()

24

In [95]:
b.sum(axis=1)

array([ 6, 18])

https://numpy.org/doc/1.19/user/quickstart.html#quickstart-basic-operations

### Broadcasting
There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with:

In [98]:
data = np.array([1.0,2.0])
dist = data * 1.6
dist

array([1.6, 3.2])

![](https://numpy.org/doc/1.19/_images/np_multiply_broadcasting.png)
NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a ValueError.

Learn more about broadcasting here.
https://numpy.org/doc/1.19/user/basics.broadcasting.html#basics-broadcasting

### More useful array operations
This section covers maximum, minimum, sum, mean, product, standard deviation, and more

NumPy also performs aggregation functions. In addition to min, max, and sum, you can easily run mean to get the average, prod to get the result of multiplying the elements together, std to get the standard deviation, and more.

In [100]:
data.max()

2.0

In [101]:
data.min()

1.0

In [102]:
data.sum()

3.0

In [104]:
data.std()

0.5

![](https://numpy.org/doc/1.19/_images/np_aggregation.png)

In [105]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],[0.54627315, 0.05093587, 0.40067661, 0.55645993],[0.12697628, 0.82485143, 0.26590556, 0.56917101]])

It’s very common to want to aggregate along a row or column. By default, every NumPy aggregation function will return the aggregate of the entire array. To find the sum or the minimum of the elements in your array, run:

In [106]:
a.min()

0.05093587

In [107]:
a.max()

0.82485143

In [108]:
a.sum()

4.8595784

You can specify on which axis you want the aggregation function to be computed. For example, you can find the minimum value within each column by specifying axis=0.

In [109]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

The four values listed above correspond to the number of columns in your array. With a four-column array, you will get four values as your result.

Read more about array methods here.
https://numpy.org/doc/1.19/reference/arrays.ndarray.html#array-ndarray-methods